default:
  target: dev
  outputs:
    dev:
      type: synapse
      driver: 'ODBC Driver 18 for SQL Server'
      server: (DO NOT VERSION CONTROL SENSITIVE INFO!) # (Dedicated SQL endpoint of your workspace here)
      port: 1433
      database: (DO NOT VERSION CONTROL SENSITIVE INFO!)
      authentication: sql
      schema: (DO NOT VERSION CONTROL SENSITIVE INFO!)
      user: sqladminuser
      password: (DO NOT VERSION CONTROL SENSITIVE INFO!)