version: 2

sources:
  - name: dbtSchema_Arthur20240304
    database: postgres
    schema: dbtSchema_Arthur20240304
    tables:
      - name: raw_transactions
        columns:
          - name: timestamp
            data_type: timestamp without time zone
          - name: transaction_id
            data_type: character
          - name: customer_id
            data_type: smallint
        tests:
          - elementary.schema_changes_from_baseline
              fail_on_added: true
              enforce_types: true
